apiVersion: v1
kind: Service
metadata:
  name: perf-test2-app644-svc
  namespace: clawtest
  labels:
    app: perf-test2-app644
spec:
  selector:
    app: perf-test2-app644
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
